### PR TITLE
Match OAuth2 Client Abstract methods and interfaces

### PR DESCRIPTION
**Pull request by ctrlaltdylan**
- Created a `RedditUser` class that implements the `ResourceOwnerInterface`
  - Using the Facebook OAuth2 client implementation as an example
- Updated `Reddit` to include 1 method name change and a new method for creating the ResourceOwner

### CODE REVIEW

**Comment by rtheunissen** [comment]
Thanks for this @ctrlaltdylan. I'll take a closer look later when I'm not on my phone. Why did you change the namespace back, though? I intended to change it for 2.0, the next major version.

**Comment by ctrlaltdylan** [comment]
@rtheunissen no problem! Sorry I realized that after I already changed them in the files. It thought maybe it was a PHP code cleanup program error.

**Comment by rtheunissen** [comment]
No worries. It's just an effort to keep consistent with other projects. Thanks for that. I might make a few small adjustments but so far all this looks good.

**Comment by rtheunissen** [comment]
@ctrlaltdylan Happy to merge once the namespace is changed back. :+1:

**Comment by ctrlaltdylan** [comment]
@rtheunissen switched namespace back to `Concat` :beers:

**Comment by rtheunissen** [comment]
:sparkles:

**Comment by ctrlaltdylan** [comment]
:clap: :tophat: :beers:

**Pull request merged**
